### ISSUE TITLE
RuntimeError: Directory 'static' does not exist

### ISSUE THREAD

**Issue by ivanteresh** [copolio/sentry-mattermost-proxy#1]
Hi mate!

I have to thank you for this nice project. I find it very useful for building an integration between Sentry and Mattermost, as I am trying to solve the same problem right now.

Unfortunately, it looks like you have missed copying the static folder into a Docker container, and it leads to an error on the application start.
It seems like line `COPY ./static /code/static` solves the problem.

```
Traceback (most recent call last):
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/app/main.py", line 13, in <module>
    app.mount("/static", StaticFiles(directory="static"), name="static")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ivanteresuk/dev/sentry-mattermost-proxy/venv/lib/python3.11/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static' does not exist
```

**Comment by copolio** [comment]
Hi :) thanks for spotting that! I've fixed it and pushed the changes right away 👍
